### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by kifirkin** [nfroidure/gulp-iconfont#170]
```
npm install --save-dev gulp-iconfont@latest
npm WARN deprecated gulp-util@2.2.20: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm ERR! code EINTEGRITY
npm ERR! sha1-XgIK/m5kMofzrXaHq+0g/mVOsyk= integrity checksum failed when using sha1: wanted sha1-XgIK/m5kMofzrXaHq+0g/mVOsyk= but got sha512-Bx4FbWMWOb2RsD+N85Gd30Of5tDZOs/BDPXrwyjs2FruZTSHUvR4DOr4vOtpIaZQKJEPh69nEje6rdGDqod4hg== sha1-mnZP3f7BS+THPVJeHfKIuBUtpQk=. (7966 bytes)
```

```
node --version
v8.11.1

npm --version
5.10.0
```

**Comment by NaridaL** [comment]
You try removing package-lock.json and node_modules?

**Comment by alexmironof** [comment]
I have no `package-lock.json` only `npm-shrinkwrap.json`, also deleted this and deleted `node_modules` folder and nothing helps

**Comment by alexmironof** [comment]
I think it is a problem with iconfont's `package-lock.json`... This integrity doesnt match
```
    "ttf2woff2": {
      "version": "2.0.3",
      "resolved": "https://registry.npmjs.org/ttf2woff2/-/ttf2woff2-2.0.3.tgz",
      "integrity": "sha1-XgIK/m5kMofzrXaHq+0g/mVOsyk=",
      "requires": {
        "bindings": "^1.2.1",
        "bufferstreams": "^1.1.0",
        "nan": "^2.1.0",
        "node-gyp": "^3.0.3"
      }
```

**Comment by alexmironof** [comment]
Its https://github.com/nfroidure/ttf2woff2 error. Without it everything is ok

**Comment by NaridaL** [comment]
It seems to be working fine locally and on the travis build? Can you try updating to the latest node LTS version (8.11.3)? Googling shows similar errors on 8.* Other suggestions include clearing the npm cache.

**Comment by alexmironof** [comment]
```
node --version
v8.11.3

npm --version
6.1.0

npm cache --force clean
npm WARN using --force I sure hope you know what you are doing.
```

Nothing helps 😢

**Comment by alexmironof** [comment]
By the way I’m on windows 10

**Comment by joanjane** [comment]
Hi!
I've been using this package for a while and now that gulp-util is deprecated, it shows a warning for using a dependency `gulp-spawn@0.4.0`, which still uses gulp-util.

I've created an issue to that repo https://github.com/hparra/gulp-spawn/issues/18 which seems to be ready for a release removing this deprecated dependencies. You should follow it to be uptodate to this topic.

Cheers

**Comment by NaridaL** [comment]
I published a version with updated dependencies.

**Comment by alexmironof** [comment]
@NaridaL still getting integrity checksum error 😟 
`ttf2woff2` version `2.0.3` is broken, while version `2.0.2` is working fine

**Comment by NaridaL** [comment]
@alexmironof 

```
aval@aval-pc MINGW64 ~/Downloads
$ wget https://registry.npmjs.org/ttf2woff2/-/ttf2woff2-2.0.3.tgz
Downloading...
Done!

aval@aval-pc MINGW64 ~/Downloads
$ cat ttf2woff2-2.0.3.tgz | npx srisum -a sha1
npx: installed 53 in 2.807s
sha1-XgIK/m5kMofzrXaHq+0g/mVOsyk= -
```

Do you get the same result?

You are 100% sure it's not a cache issue? https://github.com/nodejs/node/issues/13635 has some people saying `npm cache clean` isn't enough...

**Comment by alexmironof** [comment]
@NaridaL I've tried all possible variants:
- cleaned npm cache
- deleted %appdata%/npm-cache
- reinstalled node 

result for your suggestion is the same:
```
$ cat ttf2woff2-2.0.3.tgz | npx srisum -a sha1
npx: installed 53 in 9.234s
sha1-XgIK/m5kMofzrXaHq+0g/mVOsyk= -
```

I'm trying to install `gulp-icon` font to clean directory where just init clean `package.json` with `npm init` and getting same error
```
npm i gulp-iconfont --save-dev --no-shrinkwrap --update-binary
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated transformation-matrix-js@2.7.6: Package no longer supported. Contact support@npmjs.com for more info.
npm ERR! code EINTEGRITY
npm ERR! sha1-XgIK/m5kMofzrXaHq+0g/mVOsyk= integrity checksum failed when using sha1: wanted sha1-XgIK/m5kMofzrXaHq+0g/mVOsyk= but got sha512-3ps+2TS3ydSLHkLylMj2VAiI/KfJD8H5aLA3jIn9EpqwVcJVrD5yeHSeuAt1DbIRl0qcfFU5p61xQwlJrGsRnA== sha1-ozXni+AuGYd3Xghfa1P9SVhB3oc=. (7989 bytes)
npm WARN tar invalid entry
npm WARN tar invalid entry
npm WARN tar invalid entry
npm WARN tar invalid entry
npm WARN tar invalid entry
npm WARN tar invalid entry
npm WARN tar invalid entry
npm WARN tar invalid entry
npm WARN tar invalid entry
npm WARN tar invalid entry
npm WARN tar invalid entry
npm WARN tar invalid entry
npm WARN tar invalid entry
npm WARN tar invalid entry
npm WARN tar invalid entry
```

**Comment by alexmironof** [comment]
also I noticed that checksum varies every time I try to install:

```
>npm install ttf2woff2                                                                                                                                         13:28npm ERR! code EINTEGRITY
npm ERR! sha1-XgIK/m5kMofzrXaHq+0g/mVOsyk= integrity checksum failed when using sha1: wanted sha1-XgIK/m5kMofzrXaHq+0g/mVOsyk= but got sha512-3TGS7GGkYPaemV5YgyekKYPZgYEZoeZLPJm/tiln6WD9JIwVCzbrVO+PMCdsxxfUFK7L6utI6571P5toQzu4lg== sha1-DTJ2VosZioofR9lyZvpceAs0UNI=. (7989 bytes)

>npm install ttf2woff2
npm ERR! code EINTEGRITY
npm ERR! sha1-XgIK/m5kMofzrXaHq+0g/mVOsyk= integrity checksum failed when using sha1: wanted sha1-XgIK/m5kMofzrXaHq+0g/mVOsyk= but got sha512-/jUhlP4/M8wSzJcUQ14trMMIei6h6PH7xjVuLe1H8zppkKQkKsH2dW5LgMswZepUZBryCFdjYt9UccmaCBsVOw== sha1-EWt9iW8Q7mbOnnRAKlY1PE75DzI=. (7989 bytes)

>npm install ttf2woff2
npm ERR! code EINTEGRITY
npm ERR! sha1-XgIK/m5kMofzrXaHq+0g/mVOsyk= integrity checksum failed when using sha1: wanted sha1-XgIK/m5kMofzrXaHq+0g/mVOsyk= but got sha512-XKtYNpQafd6ik8MkgH+c/CkEdy0D0mZLMBRBSwK3zCUPt78OuTSW+eSyrRxT0/2nX2o1bRRkMdn4jsnct8BuzA== sha1-GYFz5WX8dBQwfsG7gf73dbI3k70=. (7989 bytes)
```

**Comment by alexmironof** [comment]
also I noticed that checksum wich I got varies every time I try to install:

```
>npm install ttf2woff2
ERR! code EINTEGRITY
npm ERR! sha1-XgIK/m5kMofzrXaHq+0g/mVOsyk= integrity checksum failed when using sha1: wanted sha1-XgIK/m5kMofzrXaHq+0g/mVOsyk=
but got sha512-3TGS7GGkYPaemV5YgyekKYPZgYEZoeZLPJm/tiln6WD9JIwVCzbrVO+PMCdsxxfUFK7L6utI6571P5toQzu4lg==
sha1-DTJ2VosZioofR9lyZvpceAs0UNI=. (7989 bytes)

>npm install ttf2woff2
npm ERR! code EINTEGRITY
npm ERR! sha1-XgIK/m5kMofzrXaHq+0g/mVOsyk= integrity checksum failed when using sha1: wanted sha1-XgIK/m5kMofzrXaHq+0g/mVOsyk=
but got sha512-/jUhlP4/M8wSzJcUQ14trMMIei6h6PH7xjVuLe1H8zppkKQkKsH2dW5LgMswZepUZBryCFdjYt9UccmaCBsVOw==
sha1-EWt9iW8Q7mbOnnRAKlY1PE75DzI=. (7989 bytes)

>npm install ttf2woff2
npm ERR! code EINTEGRITY
npm ERR! sha1-XgIK/m5kMofzrXaHq+0g/mVOsyk= integrity checksum failed when using sha1: wanted sha1-XgIK/m5kMofzrXaHq+0g/mVOsyk=
but got sha512-XKtYNpQafd6ik8MkgH+c/CkEdy0D0mZLMBRBSwK3zCUPt78OuTSW+eSyrRxT0/2nX2o1bRRkMdn4jsnct8BuzA==
sha1-GYFz5WX8dBQwfsG7gf73dbI3k70=. (7989 bytes)
```

**Comment by NaridaL** [comment]
Which version of node are you on now? The linked issue did say there was a bug.

**Comment by alexmironof** [comment]
I've installed the latest version 
```
>node -v
v10.12.0

>npm -v
6.4.1
```
